version: '3.8'
services:
  stockeventsourcing:
    container_name: stockeventsourcing
    build:
      context: .
      target: development
    ports:
      - "8000:8000"
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - POSTGRESQL_URL=jdbc:postgresql://postgresql/stockeventsourcing
    volumes:
      - ./:/app
    depends_on:
      - postgresqldb

  postgresqldb:
    image: postgres:14.1-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
    driver: local


